package lk.ijse.finalproject.util;

public enum Route {
    REGISTER, LOGIN,MANAGER_DASHBOARD,DESIGNER_DASHBOARD,TEAMLEADER_DASHBOARD,EMPLOYEE_MANAGE,CLIENT_MANAGE,APPOINTMENT_MANAGE,CLIENT_CONSULTING,SERVICE,VENDOR_COLLABARATING,EVENT_DESIGN,WEDDING_DESIGN,ANNIVERSARY_DESIGN,VENDORS,BIRTHDAY,CONCERTS,CONFERENCE,FESTIVAL,EDUCATIONAL,SPORTS,FORGETPASSWORD;
}
